# Generated by DeepSeek
from django import template

register = template.Library()


@register.filter
def get_item(dictionary, key):
    """Get dictionary[key] or None if not found"""
    return dictionary.get(key)


@register.filter
def get_nested(dictionary, keys):
    if not isinstance(keys, list):
        keys = [keys]

    for key in keys:
        if isinstance(dictionary, dict):
            dictionary = dictionary.get(key)
        else:
            return None

    return dictionary
