[project]
name = "empath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.4",
    "django-bootstrap-icons>=0.9.0",
    "django-bootstrap5>=26.2",
    "django-filter>=25.2",
    "django-rest-framework>=0.1.0",
    "flaskwebgui>=1.1.9",
    "waitress>=3.0.2",
    "whitenoise>=6.12.0",
]
