# Generated by Django 6.0.4 on 2026-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='employers',
            field=models.ManyToManyField(related_name='contact_employers', to='SearchTracker.employer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_titles',
            field=models.ManyToManyField(related_name='contact_job_titles', to='SearchTracker.title'),
        ),
    ]
