# Generated by Django 6.0.4 on 2026-05-12 06:11

import SearchTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0002_contact_employers_contact_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default=SearchTracker.models.Contact.SexOptions['MALE'], max_length=8),
        ),
    ]
