# Generated by Django 6.0.4 on 2026-05-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0003_contact_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateSnippet',
            new_name='Snippet',
        ),
    ]
