# Generated by Django 6.0.4 on 2026-05-16 18:21

import SearchTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0004_rename_templatesnippet_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='citizen_type',
            field=models.CharField(choices=[('Worker', 'WORKER'), ('Talent', 'TALENT'), ('Drone', 'DRONE'), ('Technician', 'TECHNICIAN'), ('Doctor', 'DOCTOR'), ('Librarian', 'LIBRARIAN'), ('Engineer', 'ENGINEER'), ('Empath', 'EMPATH'), ('Thinker', 'THINKER'), ('Transcend', 'TRANSCEND'), ('Nerve Stapled', 'NERVE_STAPLED')], default=SearchTracker.models.Contact.CitizenClassOptions['WORKER'], max_length=16),
        ),
        migrations.AlterField(
            model_name='contact',
            name='employers',
            field=models.ManyToManyField(blank=True, related_name='contact_employers', to='SearchTracker.employer'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_titles',
            field=models.ManyToManyField(blank=True, related_name='contact_job_titles', to='SearchTracker.title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='resumes_for_title',
            field=models.ManyToManyField(blank=True, related_name='resumes_for_title', to='SearchTracker.resumetitle'),
        ),
    ]
