# Generated by Django 6.0.4 on 2026-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0005_alter_contact_citizen_type_alter_contact_employers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
