# Generated by Django 6.0.4 on 2026-05-25 02:00

import SearchTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0007_contacticon_remove_contact_citizen_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacticon',
            name='icon_sex',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Either', 'EITHER')], default=SearchTracker.models.ContactIcon.SexOptions['EITHER'], max_length=8),
        ),
    ]
