# Generated by Django 6.0.4 on 2026-06-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0008_contacticon_icon_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='SearchTracker/files/pdfs/'),
        ),
    ]
