# Generated by Django 6.0.4 on 2026-06-01 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0009_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='resumes_for_title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='resume_title',
        ),
        migrations.DeleteModel(
            name='ResumeTitle',
        ),
        migrations.AddField(
            model_name='document',
            name='resume_title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resume_title', to='SearchTracker.title'),
            preserve_default=False,
        ),
    ]
