# Generated by Django 6.0.4 on 2026-06-02 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0010_remove_title_resumes_for_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='employers',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='job_titles',
        ),
        migrations.AlterField(
            model_name='contactemployertitle',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='SearchTracker.contact'),
        ),
    ]
