# Generated by Django 6.0.4 on 2026-06-29 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0011_remove_contact_employers_remove_contact_job_titles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_application_location',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SearchTracker.location'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobApplicationLocation',
        ),
    ]
