# Generated by Django 6.0.4 on 2026-06-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTracker', '0012_remove_jobapplication_job_application_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
