// Adapted from a script generated by DeepSeek

$(document).ready(function () {
  // 1. Column definitions – status is at index 8
  const colDefs = [
    { data: "id", visible: false },
    {
      data: "position_title",
      render: function (data) {
        return data ? data.title : "";
      },
    },
    {
      data: "employer",
      render: function (data) {
        return data && data.name ? data.name : data;
      },
    },
    { data: "precise_position_title" },
    {
      data: "original_post_link",
      render: function (data) {
        if (!data) return "";
        return `<a href="/" onclick=openInBrowser('${data}')>Link</a>`;
      },
    },
    { data: "date_sourced" },
    { data: "date_applied" },
    { data: "deadline" },
    { data: "status" },
    {
      data: "resume",
      render: function (data) {
        if (!data) return "";
        var docId = data.id || data;
        var docName = data.name || data.filename || "Resume";
        return '<a href="/documents/' + docId + '/">' + docName + "</a>";
      },
    },
  ];

  // 2. Initialize DataTable with a regular function for drawCallback
  const table = $("#applications-table").DataTable({
    processing: true,
    serverSide: false,
    ajax: {
      url: `${window.origin}/api/applications/`,
      dataSrc: "",
    },
    columns: colDefs,
    order: [[0, "desc"]],
    searching: true,
    autoWidth: true,
    responsive: true,
    drawCallback: function (settings) {
      // ← regular function
      const api = this.api();
      $("td.editable-cell", api.table().body()).editable("destroy");
      initStatusEditable(api);
    },
  });

  // 3. Helper: PATCH with fetch
  async function patchData(url, data) {
    const response = await fetch(url, {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": getCsrfTokenFromPage(), // your CSRF helper
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      let errorMessage = "Server error";
      try {
        const errData = await response.json();
        errorMessage = errData.detail || errData.message || errorMessage;
      } catch (err) {
        errorMessage = response.statusText || errorMessage;
      }
      throw new Error(errorMessage);
    }
    return await response.json();
  }

  // 4. Make status column (index 8) editable
  function initStatusEditable(api) {
    const rows = api.rows().data();
    api
      .column(8)
      .nodes()
      .each(function (cell, index) {
        const rowData = rows[index];
        if (!rowData) return;

        $(cell)
          .editable({
            type: "select",
            mode: "inline",
            source: [
              { value: "Sourced", text: "Sourced" },
              { value: "Applied", text: "Applied" },
              { value: "Interviewing", text: "Interviewing" },
              { value: "Negotiating", text: "Negotiating" },
              { value: "Accepted", text: "Accepted" },
            ],
            value: rowData.status,
            url: function (params) {
              return patchData(`/api/applications/${rowData.id}/`, {
                status: params.value,
              });
            },
            success: function (response, newValue) {
              rowData.status = newValue;
            },
            error: function (xhr, status, error) {
              console.error("Update failed:", error);
            },
          })
          .addClass("editable-cell");
      });
  }
});
