# import time
# import threading
from django.views.generic import ListView, TemplateView
from .models import Contact, Document, TemplateSnippet
from .filters import ContactFilter
from django.shortcuts import redirect, render
from django.http import Http404
import os
import signal
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

# helper constants

APP_NAME = "SearchTracker"
ADMIN_PREFIX = f"/admin/{APP_NAME}/"
ICONS_PREFIX = "SearchTracker/images/icons/"

# variables
# _last_heartbeat = time.time()
# _heartbeat_lock = threading.Lock()
# _watchdog_thread_started = False

# non view utilities
# Adapted from code generated by DeepSeek
# def _watchdog():
#     global _last_heartbeat
#     while True:
#         if time.time() - _last_heartbeat > 60 * 60 * 1000:
#             close()
#             break

#         time.sleep(5)


# def _start_watchdog():
#     global _watchdog_thread_started
#     if not _watchdog_thread_started:
#         _watchdog_thread_started = True
#         thread = threading.Thread(target=_watchdog, daemon=True)
#         thread.start()


# class based views

# abstract class based views

class FilteredListView(ListView):
    """
    From Dan Poirier's "Dan's Cheat Sheets"
    https://cheat.readthedocs.io/en/latest/index.html
    """
    filterset_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(
            self.request.GET, queryset=queryset)

        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filterset"] = self.filterset
        return context

# Template Views


class HomeTemplateView(TemplateView):
    template_name = f"{APP_NAME}/home.html"

# ListViews


class ContactListView(FilteredListView):
    model = Contact
    filterset_class = ContactFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["add_url"] = f"{ADMIN_PREFIX}contact/add/"

        context["contact_types"] = {
            "Doctor": {"Male": f"{ICONS_PREFIX}doctor.png"},
            "Drone": {"Female": f"{ICONS_PREFIX}drone-female.png", "Male": f"{ICONS_PREFIX}drone-male.png"},
            "Empath": {"Female": f"{ICONS_PREFIX}empath.png"},
            "Engineer": {"Male": f"{ICONS_PREFIX}engineer.png", "Female": f"{ICONS_PREFIX}engineer.png"},
            "Librarian": {"Male": f"{ICONS_PREFIX}librarian.png"},
            "Talent": {"Female": f"{ICONS_PREFIX}talent-female.png", "Male": f"{ICONS_PREFIX}talent-male.png"},
            "Techician": {"Male": f"{ICONS_PREFIX}technician.png", "Female": f"{ICONS_PREFIX}technician.png"},
            "Thinker": {"Male": f"{ICONS_PREFIX}thinker.png"},
            "Transcend": {"Male": f"{ICONS_PREFIX}transcend.png", "Female": f"{ICONS_PREFIX}transcend.png"},
            "Worker": {"Female": f"{ICONS_PREFIX}worker-female.png", "Male": f"{ICONS_PREFIX}worker-male.png"}
        }

        return context


# Delete Views


# function based views


def documents(request):
    return render(request, f"{APP_NAME}/documents.html", {
        "documents": Document.objects.all(),
        "documents_count": Document.objects.count(),
        "add_document_url": f"{ADMIN_PREFIX}document/add/",
        "snippets": TemplateSnippet.objects.all(),
        "snippets_count": TemplateSnippet.objects.count(),
        "add_snippet_url": f"{ADMIN_PREFIX}templatesnippet/add/",
    })


def delete_template_snippet(request, pk):
    try:
        template_snippet = TemplateSnippet.objects.get(pk=pk)
        if request.method == "POST":
            template_snippet.delete()
            return redirect(f"{APP_NAME}:documents")
    except TemplateSnippet.DoesNotExist:
        raise Http404(f"Template Snippet with id={pk} does not exist")

# utility views

# # Adapted from code generated by DeepSeek
# @csrf_exempt
# def heartbeat(request):
#     global _last_heartbeat
#     with _heartbeat_lock:
#         _last_heartbeat = time.time()
#     _start_watchdog()
#     return HttpResponse("Shutting down...")


@csrf_exempt
def close(request):
    # Get the process group ID of the current process
    pgid = os.getpgid(os.getpid())
    # Send SIGKILL to every process in this group
    os.killpg(pgid, signal.SIGKILL)
