# import time
# import threading
from django.views.generic import DetailView, ListView, TemplateView
from .models import Contact, ContactIcon, Document, Snippet
from .filters import ContactFilter
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.http import Http404, HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import webbrowser
import os
import signal


# Create your views here.

# helper constants

APP_NAME = "SearchTracker"
ADMIN_PREFIX = f"/admin/{APP_NAME}/"
ICONS_PREFIX = f"{APP_NAME}/images/icons/"
AUDIO_PREFIX = f"{APP_NAME}/audio/"

# variables

# contact_types = {
#     "Doctor": {"Male": f"{ICONS_PREFIX}doctor.png"},
#     "Drone": {"Female": f"{ICONS_PREFIX}drone-female.png", "Male": f"{ICONS_PREFIX}drone-male.png"},
#     "Empath": {"Female": f"{ICONS_PREFIX}empath.png"},
#     "Engineer": {"Male": f"{ICONS_PREFIX}engineer.png", "Female": f"{ICONS_PREFIX}engineer.png"},
#     "Librarian": {"Male": f"{ICONS_PREFIX}librarian.png"},
#     "Talent": {"Female": f"{ICONS_PREFIX}talent-female.png", "Male": f"{ICONS_PREFIX}talent-male.png"},
#     "Technician": {"Male": f"{ICONS_PREFIX}technician.png", "Female": f"{ICONS_PREFIX}technician.png"},
#     "Thinker": {"Male": f"{ICONS_PREFIX}thinker.png"},
#     "Transcend": {"Male": f"{ICONS_PREFIX}transcend.png", "Female": f"{ICONS_PREFIX}transcend.png"},
#     "Worker": {"Female": f"{ICONS_PREFIX}worker-female.png", "Male": f"{ICONS_PREFIX}worker-male.png"}
# }

# citizen_type_options_raw = Contact._meta.get_field(
#     "citizen_type").__dict__["_choices"]

# citizen_type_options = []

# for citizen_type in citizen_type_options_raw:
#     citizen_type_options.append(citizen_type[0])

# utility vars
# _last_heartbeat = time.time()
# _heartbeat_lock = threading.Lock()
# _watchdog_thread_started = False

# non view utilities
# Adapted from code generated by DeepSeek
# def _watchdog():
#     global _last_heartbeat
#     while True:
#         if time.time() - _last_heartbeat > 60 * 60 * 1000:
#             close()
#             break

#         time.sleep(5)


# def _start_watchdog():
#     global _watchdog_thread_started
#     if not _watchdog_thread_started:
#         _watchdog_thread_started = True
#         thread = threading.Thread(target=_watchdog, daemon=True)
#         thread.start()


# class based views

# abstract class based views

class FilteredListView(ListView):
    """
    From Dan Poirier's "Dan's Cheat Sheets"
    https://cheat.readthedocs.io/en/latest/index.html
    """
    filterset_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(
            self.request.GET, queryset=queryset)

        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filterset"] = self.filterset
        return context

# Template Views


class HomeTemplateView(TemplateView):
    template_name = f"{APP_NAME}/home.html"

# ListViews


class ContactListView(FilteredListView):
    model = Contact
    context_object_name = "contacts"
    filterset_class = ContactFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["add_url"] = f"{ADMIN_PREFIX}contact/add/"
        context["AUDIO_URL_PREFIX"] = AUDIO_PREFIX

        return context

# DetailViews


class ContactDetailView(DetailView):
    model = Contact
    context_object_name = "contact"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

# Delete Views


# function based views


def documents(request):
    return render(request, f"{APP_NAME}/documents.html", {
        "documents": Document.objects.all(),
        "documents_count": Document.objects.count(),
        "add_document_url": f"{ADMIN_PREFIX}document/add/",
        "snippets": Snippet.objects.all(),
        "snippets_count": Snippet.objects.count(),
        "add_snippet_url": f"{ADMIN_PREFIX}snippet/add/",
    })


@require_http_methods(["POST"])
def change_contact_icon(request, pk):
    contact = get_object_or_404(Contact, pk=pk)

    icon_id = request.POST.get("icon-id")
    if not icon_id:
        return JsonResponse({"success": False, "error": "Missing icon_id"}, status=400)

    try:
        new_icon = ContactIcon.objects.get(pk=icon_id)
    except ContactIcon.DoesNotExist:
        return JsonResponse({"success": False, "error": "Invalid icon ID"}, status=400)

    contact.contact_icon = new_icon
    contact.save()

    return JsonResponse({"success": True, "redirect_url": reverse_lazy(f"{APP_NAME}:contacts")})


def delete_snippet(request, pk):
    try:
        snippet = Snippet.objects.get(pk=pk)
        if request.method == "POST":
            snippet.delete()
            return redirect(f"{APP_NAME}:documents")
    except Snippet.DoesNotExist:
        raise Http404(f"Snippet with id={pk} does not exist")

# utility views

# # Adapted from code generated by DeepSeek
# @csrf_exempt
# def heartbeat(request):
#     global _last_heartbeat
#     with _heartbeat_lock:
#         _last_heartbeat = time.time()
#     _start_watchdog()
#     return HttpResponse("Shutting down...")


@csrf_exempt
def open_browser(request):
    if request.method == "POST":
        url = request.POST.get("url")
        if url:
            webbrowser.open(url)
            return HttpResponse(f"Browser successfully opened to {url}")

    return HttpResponse("Invalid request", status=400)


@csrf_exempt
def close(request):
    # Get the process group ID of the current process
    pgid = os.getpgid(os.getpid())
    # Send SIGKILL to every process in this group
    os.killpg(pgid, signal.SIGKILL)
